### ISSUE TITLE
SESSION namespace

### ISSUE THREAD

**Issue by mudrd8mz** [YU-MITC/moodle-atto_yukaltura#1]
These days, plugins are generally discouraged from accessing the SESSION global directly. It is generally cleaner to use MUC cache of the "session" to achieve the same result.

If there is a good reason to store things directly into the SESSION, plugins should keep some sane namespace there to avoid conflicts with other subsystems and plugins.

Here https://github.com/YU-MITC/moodle-atto_yukaltura/blob/520dfd6e2c019bc1a105f5723599a98b498ea059/atto_selector.php#L79 you store a value into `$SESSION->selector` which is too generic and can potentially conflict with other plugins that would do the same.

Better to use something like `$SESSION->atto_yukaltura->selector`

**Comment by YU-MITC** [comment]
Hello, @mudrd8mz 

Thank you for your support and advice.
We fixed variable names about SESSION namespace.
